CREATE TABLE short_urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_code VARCHAR(32) NOT NULL,
    long_url VARCHAR(2048) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    click_count BIGINT NOT NULL DEFAULT 0,
    last_accessed_at TIMESTAMP WITH TIME ZONE,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_short_urls_short_code UNIQUE (short_code)
);

CREATE INDEX idx_short_urls_expires_at ON short_urls (expires_at);
CREATE INDEX idx_short_urls_created_at ON short_urls (created_at);
